version: "3.8"

services:
  backend:
    build:
      context: ./backend
    volumes:
      - ./backend/app:/app/app
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    command: >
      uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app/app

  frontend:
    build:
      context: ./frontend
    volumes:
      - ./frontend:/app
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true
    command: npm start
